/**
 * Generator for QDS UI State Variants
 *
 * This script generates Tailwind @custom-variant declarations for all data attribute states.
 * Run this to generate the CSS, then copy it into your global.css file.
 *
 * Usage:
 *   bun run docs/generate-ui-variants.ts
 */

type DataAttributeState =
  | "invalid"
  | "required"
  | "disabled"
  | "readonly"
  | "checked"
  | "selected"
  | "pressed"
  | "open"
  | "closed"
  | "highlighted"
  | "current"
  | "mixed"
  | "empty"
  | "orientation";

/**
 * Generate positive and negative variant CSS for a given state
 *
 * @param state - The state name (e.g. "checked", "disabled")
 * @returns CSS string with @custom-variant declarations
 */
function generateVariant(state: DataAttributeState): string {
  const variantName = `ui-${state}`;
  const negatedVariantName = `not-ui-${state}`;
  const dataAttr = `data-${state}`;

  return `/**
 * ${variantName}: Apply styles when nearest component root has ${dataAttr}
 * Automatically scopes to prevent nested components from inheriting state
 */
@custom-variant ${variantName} (
  /* Descendant of root with ${dataAttr}, stops at nearest root boundary */
  [data-qds-root][${dataAttr}]:has(&):not(:has([data-qds-root] &)) &,
  /* Direct match on element itself */
  [${dataAttr}]&
);

/**
 * ${negatedVariantName}: Apply styles when nearest component root does NOT have ${dataAttr}
 * Automatically scopes to prevent nested components from inheriting state
 */
@custom-variant ${negatedVariantName} (
  /* Descendant of root without ${dataAttr}, stops at nearest root boundary */
  [data-qds-root]:not([${dataAttr}]):has(&):not(:has([data-qds-root] &)) &,
  /* Direct match on element itself */
  :not([${dataAttr}])&
);`;
}

/**
 * Generate all variants
 */
export function generateAllVariants(): string {
  const states: DataAttributeState[] = [
    "invalid",
    "required",
    "disabled",
    "readonly",
    "checked",
    "selected",
    "pressed",
    "open",
    "highlighted",
    "current",
    "mixed",
    "empty",
    "orientation"
  ];

  const header = `/**
 * QDS UI State Variants
 * 
 * These custom variants enable state-based styling that automatically scopes
 * to the nearest component root, preventing style leakage in nested components.
 * 
 * Usage:
 *   ui-checked:bg-blue-500
 *   not-ui-disabled:opacity-100
 *   ui-open:rotate-180
 * 
 * Generated by: docs/generate-ui-variants.ts
 * DO NOT EDIT MANUALLY - Run the generator script to update
 */
`;

  const variants = states.map((state) => generateVariant(state)).join("\n\n");

  return `${header}\n${variants}`;
}
